apiVersion: v1
kind: Pod
metadata:
  labels:
    jmeter-label: jmeter-master
    jenkins-label: jenkins-slave
spec:
  serviceAccountName: jenkins-release
  containers:
    - name: maven
      image: maven:alpine
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1024Mi"
          cpu: "500m"
      volumeMounts:
        - mountPath: /root/.m2
          name: m2-volume
    - name: kubehelm
      image: dtzar/helm-kubectl:2.14.3
      command:
        - cat
      tty: true
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "200m"
      volumeMounts:
#        - mountPath: /root/.kube
#          name: kube-volume
        - mountPath: /root/.helm
          name: helm-volume
  volumes:
#    - name: kube-volume
#      hostPath:
#            # directory location on host
#            path: /Users/asankav/.kube
#            # this field is optional
#            type: Directory
#    - name: helm-volume
#      hostPath:
#            # directory location on host
#            path: /Users/asankav/.helm
#            # this field is optional
#            type: Directory
    - name: m2-volume
      persistentVolumeClaim:
        claimName: maven-pv-claim
    - name: helm-volume
      persistentVolumeClaim:
        claimName: helm-pv-claim